### ISSUE TITLE
Targeting .NET framework v 4.5

### ISSUE THREAD

**Issue by kburnik** [ion-sapoval/google-measurement-protocol-dotnet#1]
Is there a suggestion on how to target lower .NET framework versions, other than attempting to checkout and retarget manually?

Not sure about the MIT license, but would it be ok for me to publish googlemeasurementprotocolnet45 to NuGet?

**Comment by ion-sapoval** [comment]
Library is now targeting .net framework 4.5.1. 
If you want to target another .net version then you'll have to retarget manually.
Regarding the licence, you can do whatever you want with sources of this library.
