### ISSUE TITLE
ProductPrice and ProductImpressionPrice have wrong value type

### ISSUE THREAD

**Issue by tompazourek** [ion-sapoval/google-measurement-protocol-dotnet#10]
Hi Ion, just noticed this issue:

The "ProductPrice" and "ProductImpressionPrice" parameters accept `string` value, but they should accept `decimal` value instead.

Is it intentional or a bug?

Thanks, great little library :)

EDIT: Also "ProductQuantity" should accept an `integer`, not a `string`. 
And I noticed that the "ProductCustomMetric" and "ProductImpressionCustomMetric" have the same issue.

**Comment by ion-sapoval** [comment]
Hi Tom,

It's a bug.
I'll fix it tomorrow.

Thx for reporting the issue!

**Comment by ion-sapoval** [comment]
Fixed in release 1.4.2.

**Comment by tompazourek** [comment]
Thank you.
