### ISSUE TITLE
Sign the assembly with a Strong Name

### ISSUE THREAD

**Issue by jagbarcelo** [ion-sapoval/google-measurement-protocol-dotnet#11]
Are you planning to sign the assembly with a Strong Name? Right now we are having some issues with the current release 1.4.2 because we are using it through a wrapper dll and the target project complains with a System.TypeInitializationException with an inner FileLoadException.

Curiously, it complains about not being able to load 'GoogleMeasurementProtocol, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null', note that the version 1.4.1.0 is not the installed version 1.4.2

Thanks.

**Comment by ion-sapoval** [comment]
Apparently in release 1.4.2 assembly version wasn't updated to 1.4.2.
Signing the assembly with a Strong Name is not a bad idea.
Probably in the next release, when this library will be converted to a .Net Standard library, I will sign it.

Cheers!

**Comment by ion-sapoval** [comment]
In the latest release (1.4.3) assembly has been signed with a Strong Name.
