### ISSUE TITLE
Building audience

### ISSUE THREAD

**Issue by wunpac** [ion-sapoval/google-measurement-protocol-dotnet#12]
I've been using measurement protocol for a few years now. Everything works great except - in Google Analytics audience membership doesn't grow (Admin > Audience Definitions > Audiences > New Audience > All Users).

Any ideas why? In Reports > Audience > Overview all the data is there for sessions, users, pageviews etc. so I know I'm sending the data correctly.

Google looked into this for me and they simply said after a few weeks going backward and forwards that they can't support this issue as I'm using a non standard implementation (i.e. not java script)

A help greatly appreciated. I want to grow an audience for re-marketing purposes.

**Comment by ion-sapoval** [comment]
Unfortunately I don't have any useful info or advice regarding your issue.

Regards
