### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by wunpac** [ion-sapoval/google-measurement-protocol-dotnet#13]
If I upgrade to version 1.4.0 or higher I get the error

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void GoogleMeasurementProtocol.GoogleAnalyticsRequestFactory..ctor(System.String, System.Net.IWebProxy)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Any help is hugely appreciated

**Comment by ion-sapoval** [comment]
Constructor which accepts combination of string and IWebProxy wasn't removed and it is still available: 
`public GoogleAnalyticsRequestFactory(string trackingId, IWebProxy proxy = null)`
Can you please provide an example of instantiation of GoogleAnalyticsRequestFactory from your code.

**Comment by wunpac** [comment]
Hi,

var factory = new GoogleAnalyticsRequestFactory("UA-000000000-0");
var request = factory.CreateRequest(HitTypes.PageView);

This works for version 1.3.6 and lower.
This code is in a service (_googleAnalyticsService). The error occurs when I call the method (PageViewClients) in the service

_googleAnalyticsService.PageViewClients(googleMeasurementProtocolParameter); //error occurs here

Thank you for helping

**Comment by ion-sapoval** [comment]
Your sample code is ok.
What version of .Net Framework are you using?

**Comment by wunpac** [comment]
I'm using .net 4.5.1

If I switch between your library version 1.3.6 and 1.4.0 I can make the problem appear and disappear

**Comment by wunpac** [comment]
I'm using VS 2017 btw. Not sure if that's relevant

**Comment by ion-sapoval** [comment]
I cannot reproduce your issue. I'm using the exact setup that you have: .net framework 4.5.1 + VS 2017 and everything works fine.
The major difference between 1.3.6 and newer versions is that starting with v. 1.4.0 there is a dependence on Newtonsoft.Json (>= 9.0.0). You can check that you have this dependency in place.
You could also try to create a console application from scratch and install latest version of the package  (or at least 1.4.2) and make some tests to see if the problem persists.
