### ISSUE TITLE
Cannot install NuGet package for version 1.4.3

### ISSUE THREAD

**Issue by jagbarcelo** [ion-sapoval/google-measurement-protocol-dotnet#14]
Hi Ion,

I contacted you some weeks ago about your package not being signed with a strong name. In the meantime I've been using a copy of your project (it was on v1.4.1 then) sitting next to the rest of my projects in a solution. Now I'm trying to remove my copy of your project and start using the NuGet version you have just published.

Whenever I try to install the package I get the following message:

`Could not install package 'GoogleMeasurementProtocol 1.4.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author`

As I see the newest version 1.4.3 (the one with a strong name) has a dependency on **.NETStandard,Version=v2.0**, and also on Newtonsoft.Json (<= 9.0.1)

My project is targeted to NETFramework,Version=v4.5.

As stated in [Version Compatibility in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility) [...]Source code written for one version of the .NET Framework should compile on later versions of the .NET Framework[...]. Later in that  document reads: [...]The .NET Framework 4.5 and later versions are backward-compatible with apps that were built with earlier versions of the .NET Framework[...]

Maybe you need to use `<supportedRuntime>` to your project so that it could be used in later versions?

**Comment by ion-sapoval** [comment]
Hi,

Version 1.4.3 is a .net standard 2.0 library which is compatible with .Net Framework >= 4.6.1.
You have 3 options:

1.  Change target framework version of your project to 4.6.1 or greater
2.  Install version 1.4.1 which has the exact same base code (without strong name signing and .net standard targeting), but is targeting .net framework 4.5
3.  Get the source code from the repo and update it to a suitable form for you

Cheers!
