### ISSUE TITLE
Support for decimal values in custom metrics

### ISSUE THREAD

**Issue by tompazourek** [ion-sapoval/google-measurement-protocol-dotnet#15]
The `ProductCustomMetric` class now only accepts integer values.

This is recommended for Custom metrics that are set up as *Time* or *Integer* type.

However, Google also allows to set up a Custom metric with the *Currency* type, and accepts decimal values there.

The library should ideally support both.

> Custom metrics with a type of Integer or Time should be sent using integers, while custom metrics with a type of Currency may be sent as fixed decimal values appropriate to the local currency.
― https://support.google.com/analytics/answer/2709828?hl=en

In the [Measurement Protocol Reference](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters), the Product Custom Metric value type is Integer, and the Custom Metric value type says Number. But I believe it should still work with decimal values in both cases if a custom metric is configured as Currency type. And yes, you can configure a product-level custom metric with Currency type, I've tried that. So it shouldn't really be an issue, the reference is just not 100% correct there.

**Comment by ion-sapoval** [comment]
Added support for decimal values in custom metrics in v. 2.0.0
