### ISSUE TITLE
2.0 Release Notes or Upgrade Guide

### ISSUE THREAD

**Issue by benmccallum** [ion-sapoval/google-measurement-protocol-dotnet#18]
Hey, We're using 1.4.3 and I'd like to upgrade to 2.0.0 but have no idea what (if any?) breaking changes there would be. Are you able to document something quickly in the readme? Thanks!

**Comment by ion-sapoval** [comment]
Hi,

In the [release section](https://github.com/ion-sapoval/google-measurement-protocol-dotnet/releases) you can find release changes description. The only breaking change in v 2.0.0 is removal of non-async methods.

Cheers!

**Comment by benmccallum** [comment]
Ah perfect, I didn't look hard enough.
