### ISSUE TITLE
Throw/handle given API limitations (size and hits)

### ISSUE THREAD

**Issue by benmccallum** [ion-sapoval/google-measurement-protocol-dotnet#19]
Wondering if request limitations could be handled by this wrapper. 

For single hit requests:
- Can't find anything just now, but the batch limitations mentions there are for single requests too...

For batch requests:
- https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch
- For instance, max of 20 hits per batch, max size 16Kbytes. If consumer passes more, could that be broken up and sent in multiple batch requests for them? 
- For max size of 8Kbytes per hit, I guess the wrapper would have to throw a validation exception.

**Comment by ion-sapoval** [comment]
There is a validation for max of 20 hits per batch (an ApplicationException is thrown), size constraints aren't enforced. In the next months I would try to add these too, or maybe if you have time you can make a pull request with these changes.

**Comment by benmccallum** [comment]
It's probably more work than it's worth, I think the size constraints might even vary per param and the docs are quite all over the place. Definitely a low priority. 8KB seems to be a pretty large request from my numbers.
