### ISSUE TITLE
Support for hit types other than pageview

### ISSUE THREAD

**Issue by kburnik** [ion-sapoval/google-measurement-protocol-dotnet#2]
Sorry for spamming. 

Any plans to support hit types like "screenview" and others?

*\* EDIT **: This is regarding the factory method for requests which only supports pageview hits.
Other types are only able to be created manually.

**Comment by ion-sapoval** [comment]
Library is supporting all hit types ( 'pageview', 'screenview', 'event', 'transaction', 'item', 'social', 'exception', 'timing').
