### ISSUE TITLE
Make Parameters and ProtocolVersion more robust

### ISSUE THREAD

**Issue by benmccallum** [ion-sapoval/google-measurement-protocol-dotnet#20]
Currently a request created by the factory always gets added with a default protocol version parameter of 1.
https://github.com/ion-sapoval/google-measurement-protocol-dotnet/blob/cada73e9dc8fd79b42ecd5397c26e87135a3cbcc/src/GoogleMeasurementProtocol_NetStandard/GoogleAnalyticsRequestFactory.cs#L123

In future, if a v2 or whatever came out, this could be a bit of a nightmare as you'd have to leave your current code in this library setting v1 to be backwards compatible, otherwise you'd break it for all consumers. Then consumers would have to set themselves, probably trying to add their own param value but that'd just add a dupe to the list and that'd be a non-obvious bug. Instead, they'd have to delete the original with something like:
```
var versionParam = new Params.General.ProtocolVersion("2");
request.Parameters.RemoveAll(p => p.Name == versionParam.Name);
request.Parameters.Add(versionParam);
```

Maybe we could add a `protocolVersion` argument to the factory's constructor so this value is always supplied by the user?

In terms of generally making the parameters list more robust to duplicates, we could either make adding a dupe impossible by making that collection a custom type with custom `Add` method, or maybe it's just easier to add another Validator that checks for dupes at send time and throws, either way a develop will find out pretty quick!

**Comment by ion-sapoval** [comment]
When next version of the Google Measurement Protocol will come out it will bring breaking changes 

> The Protocol version. The current value is '1'. This will only change when there are changes made that are not backwards compatible.

that means we will be forced to release a new version of the library and depending of the version you want to use you'll choose an older or newer nuget package, so there is no need to expose version parameter.

Regarding parameter duplication, it is a nice to have feature but it is for now out of scope of the library. In case you want to contribute to the project by implementing this part, you're more then welcome.

Cheers!

**Comment by benmccallum** [comment]
Yea as long as you release a major version when you update the protocol version param you're setting internally I don't see an issue.

I think I'll add a validator when I get a moment that checks for dupes. Much less work than enforcing uniqueness at the data type. Bit busy trying to get a current project over the line, but will try soon!

Edit: Actually potentially it will already fail quite loudly here:
https://github.com/ion-sapoval/google-measurement-protocol-dotnet/blob/master/src/GoogleMeasurementProtocol_NetStandard/Extensions/ListExtensions.cs
