### ISSUE TITLE
ClientId / UserId inconsistent when sending batch requests

### ISSUE THREAD

**Issue by hendrik-schulte** [ion-sapoval/google-measurement-protocol-dotnet#22]
When sending a single request, you add the `clientId` / `userId` as a parameter to the Post / Get function:
``` cs
request.PostAsync(clientId);
```
When batching requests, however, there is no such parameter and you need to add the clientId parameter manually before sending the request. I think this is inconsistent especially considering that the other mandatory parameter `hitType` is a parameter of `GoogleAnalyticsRequestFactory.CreateRequest`.
I would suggest one of the following:
1. Remove the parameter from the Post/Get functions and add it to the `CreateRequest` function. This way it is the same for single and batched requests and very consistent.
2. Add an overload to Post/Get without parameters and let the user add the clientId himself

**Comment by ion-sapoval** [comment]
Added overload (see v. 2.2.0).
