### ISSUE TITLE
GenerateQueryString method in ListExtensions should be async

### ISSUE THREAD

**Issue by hoejgaard-12** [ion-sapoval/google-measurement-protocol-dotnet#24]
The GenerateQueryString method in the ListExtensions class uses ReadAsStringAsync().Result instead of awaiting the result (and making the method async).

**Comment by hoejgaard-12** [comment]
I have added a pull request with the proposed changes to the code.

**Comment by ion-sapoval** [comment]
Accepted PR. Changes will be included in the next release (in 1-2 weeks).
