### ISSUE TITLE
GA4 support

### ISSUE THREAD

**Issue by cartmax** [ion-sapoval/google-measurement-protocol-dotnet#26]
Hi, 
Is it possible to use your SDK to send analytics on new GA4 plateform ? Old analytics plateform will be deprecated by Google soon.
Do you plan to release a new version for that ? 
Regards,
Maxime

**Comment by qayyumabro** [comment]
I have the same question.

**Comment by ion-sapoval** [comment]
Hi,

Unfortunately this project is no longer maintained.

I've also added this info to the readme file.

Best,
Ion
