### ISSUE TITLE
Wrong HitType for ExceptionTrackingRequest

### ISSUE THREAD

**Issue by kburnik** [ion-sapoval/google-measurement-protocol-dotnet#3]
The code shows that hit type is Item, but it should be Exception.

https://github.com/ion-sapoval/google-measurement-protocol-dotnet/blob/master/src/GoogleMeasurementProtocol/Requests/ExceptionTrackingRequest.cs#L12

**Comment by ion-sapoval** [comment]
It's bug. I'll fix it today.
Thank you for reporting it.
