### ISSUE TITLE
Unable to install Version 1.3.3 via NuGet

### ISSUE THREAD

**Issue by kburnik** [ion-sapoval/google-measurement-protocol-dotnet#4]
When trying to update to the latest version via NuGet

**Install-Package GoogleMeasurementProtocol -Version 1.3.3**

I get the following error.

```
Update-Package : Could not install package 'GoogleMeasurementProtocol 1.3.3'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Update-Package GoogleMeasurementProtocol -ProjectName FooProject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

I have also tried to change the framework version of FooProject to 4.5 and 4.6.

Also tried doing an upgrade from 1.3.2 to 1.3.3 (Update-Package), but to no surprise it did not help. :-(

Any thoughts?

Thanks!

**Comment by ion-sapoval** [comment]
There was a problem with the nuget package for version 1.3.3. 
Please try to install 1.3.4, it should work.

**Comment by kburnik** [comment]
After some auditing, we decided to retarget the library to net45.

Thanks for the fix, though. :-)
