### ISSUE TITLE
Retarget to .NET 4.5 (instead of 4.5.1)?

### ISSUE THREAD

**Issue by dplaskon** [ion-sapoval/google-measurement-protocol-dotnet#5]
Just curious - is there a specific reason you need to target Framework 4.5.1 specifically, as opposed to just 4.5?

**Comment by ion-sapoval** [comment]
No, there is no direct dependencies on .Net Framework 4.5.1. You can recompile the library in 4.5 and it would work just fine.

**Comment by dplaskon** [comment]
That's what I've done -- I'm just curious if the "official" package could be changed to target 4.5 instead?

**Comment by ion-sapoval** [comment]
I've changed targeted framework version to 4.5.

**Comment by dplaskon** [comment]
Awesome - thanks :)
