### ISSUE TITLE
Allow developer to target the debug url to validate requests

### ISSUE THREAD

**Issue by DarkDrek** [ion-sapoval/google-measurement-protocol-dotnet#7]
See: https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits

Validation errors should raise an exception or the response content should be returned by Get/PostAsync as Task<String>?

**Comment by ion-sapoval** [comment]
Currently hits validation is not supported by google-measurement-protocol-dotnet. 
When this functionality will be added, most probably validation requests should return response content instead of throwing an Exception.

Regards

**Comment by ion-sapoval** [comment]
Added support for Hits Validation in v. 1.4.0
